import os
import numpy as np
import torch
import torch.optim as optim
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader

from sinr_sumrate import sum_rate, sum_rate_torch
from network import MultiuserAnalogPrecoderNet
from loss import concentrated_mse_loss, kkt_digital_precoder_torch
from channel_model_los import generate_channel_los
#System parameters
M, K, L, N_RF = 128, 4, 1, 4
fc, c = 100e9, 3e8
WL = c / fc
d = WL / 2
P_t = 1.0
noise_power = 0.1       
r_min = 5.0     
r_max = 80.0    

# hyperparameters
MLP_DIMS       = [512, 256, 128]
N_SAMPLES      = 20000
TRAIN_FRAC     = 0.70
VAL_FRAC       = 0.15
TEST_FRAC      = 0.15
BATCH_SIZE     = 1024
LR            =  7.5e-4
MAX_EPOCHS     = 500         # upper bound; early stopping cuts this short
SCHED_FACTOR   = 0.5
SCHED_PATIENCE = 50
SCHED_THRESH   = 1e-4
ES_PATIENCE    = 50            # early-stopping patience (epochs)
ES_MIN_DELTA   = 1e-3
SEED           = 0
RESUME         = True
VAL_EVERY = 10
#For reproducibility : starting from the same random initialization in every RUN
torch.manual_seed(SEED) #This fixes all CPU random numbers generated by PyTorch.
np.random.seed(SEED) #This fixes all numpy random numbers generators.
if torch.cuda.is_available(): 
    torch.cuda.manual_seed_all(SEED) #This will fixes all random numbers generated by GPU

if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
print(f"Device: {device}")

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MODELS_DIR = os.path.join(SCRIPT_DIR, "models")
os.makedirs(MODELS_DIR, exist_ok=True)
# Model save paths
MODEL_2_PATH = os.path.join(MODELS_DIR, "Best_comm_model_L1.pt")
LATEST_MODEL_PATH = os.path.join(MODELS_DIR, "Last_comm_model_L1.pt")

# 1. DATASET GENERATION
# generate entire dataset used in one epoch, later divide and convert to tensor
def generate_channel_dataset(n_samples, rng):
    """Generate n_samples independent multiuser near-field channel
    realizations of shape (n_samples, M, K), complex128."""
    channels = np.stack([
        generate_channel_los(K=K, M=M, d=d, wavelength=WL,
                          r_min=r_min, r_max=r_max, rng=rng)[0]
        for _ in range(n_samples)
    ]) 
    return channels # Returns numpy.ndarray - (n_samples, M, K) complex 


print(f"\nGenerating {N_SAMPLES} channel realizations (M={M}, K={K})...")
data_rng = np.random.default_rng(SEED)
H_all = generate_channel_dataset(N_SAMPLES, data_rng)  # (N_SAMPLES, M, K) complex


# 2. TRAIN / VALIDATION / TEST SPLIT (70 / 15 / 15)
n_train = int(N_SAMPLES * TRAIN_FRAC)   # 14000
n_val   = int(N_SAMPLES * VAL_FRAC)     # 3000
n_test  = N_SAMPLES - n_train - n_val   # 3000

# Shuffle once, deterministically, before slicing.
perm = data_rng.permutation(N_SAMPLES)
H_all = H_all[perm]

H_train = H_all[:n_train]
H_val   = H_all[n_train:n_train + n_val]
H_test  = H_all[n_train + n_val:]


#Pytorch Dataset
class MultiuserChannelDataset(Dataset):
    def __init__(self, H_np):
        self.H_tensor = torch.as_tensor (H_np, dtype=torch.cfloat)  # stays on device
        self.H_complex = torch.as_tensor (H_np, dtype=torch.cfloat )  # stays on CPU
        
    def __len__(self):
        return self.H_complex.shape[0]

    def __getitem__(self, idx):
        return self.H_tensor[idx], self.H_complex[idx]

#Dataset : Each Data set has H_tensor, H_complex
train_dataset = MultiuserChannelDataset(H_train)
val_dataset   = MultiuserChannelDataset(H_val)
test_dataset  = MultiuserChannelDataset(H_test)

# Data loader for each data set : The DataLoader the data set into batches, each batch having H_tensor and H_complex of size B x M xK
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,  drop_last=False)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, drop_last=False)
test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False, drop_last=False)


# Matched-filter (phase-conjugate) + ZF-digital baseline
def matched_filter_zf_baseline_rate(H_np):
    F_RF_mf = np.exp(1j * np.angle(H_np[:, :N_RF])) / np.sqrt(M)
    H_eq = H_np.conj().T @ F_RF_mf          # (K, N_RF)
    F_BB_zf = np.linalg.pinv(H_eq)          # (N_RF, K)
    pwr = np.linalg.norm(F_RF_mf @ F_BB_zf, 'fro') ** 2
    F_BB_zf *= np.sqrt(P_t / pwr)
    return sum_rate(H_np, F_RF_mf, F_BB_zf, noise_power)

# Model / optimizer / scheduler
#object of the neural network
model = MultiuserAnalogPrecoderNet(M=M, K=K,T=0, N_RF=N_RF, mlp_dims=MLP_DIMS).to(device)
# the optimizer uses the gradients to adjust the parameters.
optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4) # model.parameters() returns Every trainable parameter inside your network is collected automatically.
# mode='max' because we're tracking validation sum-rate, which should be  maximized (unlike a loss, which is minimized).
#updates the learning rate
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='max', factor=SCHED_FACTOR,
    patience=SCHED_PATIENCE, threshold=SCHED_THRESH
)

n_params = sum(p.numel() for p in model.parameters()) #counts no. of parameters

print("\n" + "=" * 55)
print("SANITY CHECKS")
print("=" * 55)
print(f"Dataset sizes            : train={len(train_dataset)}, "
      f"val={len(val_dataset)}, test={len(test_dataset)}")
print(f"Channel tensor shape     : {tuple(train_dataset.H_complex.shape[1:])} "
      f"(per-sample), dtype={train_dataset.H_complex.dtype}")
print(f"Model input tensor shape : {tuple(train_dataset.H_tensor.shape[1:])} "
      f"(per-sample), dtype={train_dataset.H_tensor.dtype}")

with torch.no_grad():
    _sanity_batch, _ = next(iter(train_loader))
    _sanity_batch = _sanity_batch.to(device)
    _sanity_out = model(_sanity_batch)
print(f"Network output shape     : {tuple(_sanity_out.shape)} "
      f"(batch, M, N_RF), dtype={_sanity_out.dtype}")
print(f"Parameter count          : {n_params:,}")
print("=" * 55)

#compute basline MF sumrate for both validation and testing dataset
def precompute_mf_rates(H_complex_tensor): #here H_complex_tensor is the entire validation or testing dataset depending on arguments passed in 157,158 line
    H_np_all = H_complex_tensor.numpy()

    return np.array([matched_filter_zf_baseline_rate(H_np_all[i]) for i in range(H_np_all.shape[0])])

val_mf_rates_cached  = precompute_mf_rates(val_dataset.H_complex)
test_mf_rates_cached = precompute_mf_rates(test_dataset.H_complex)

# Helper: run a full pass over a loader (used for validation and test)
def evaluate(loader, model, mf_rates_cached): # testing or validation, depends on the loader passed

    model.eval() # model runs in evaluation mode, ComplexBN uses the running statistics now
    val_net_rates= []  #These will store one sum-rate per channel realization.
    with torch.no_grad(): #gradients are not computed , because evaluation only needs forward flow 
        for H_tensor, H_complex in loader: 
            #loader feeds H_tensor and H_Complex batch wise with shuffling, i.e for every iteration H_tensor = BxMxK
            H_tensor = H_tensor.to(device)
            F_RF = model(H_tensor) # Size: B x M x Nrf
            F_BB, _, _ = kkt_digital_precoder_torch(H_tensor, F_RF, noise_power, P_t)  # Size: B x Nrf X K
            H_np_batch = H_complex.numpy() 
            val_net_rates.append(sum_rate_torch( H=H_tensor, F_RF=F_RF, F_BB= F_BB, noise_power= noise_power, P_t=P_t).item())

                
    return float(np.mean(val_net_rates)), float(np.mean(mf_rates_cached))

train_loss_history = []
train_rate_history = []
val_rate_history = []
def save_checkpoint(path, epoch, best_val_rate, best_epoch, epochs_no_improve):
    torch.save({
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'epoch': epoch,
        'best_val_rate': best_val_rate,
        'best_epoch': best_epoch,
        'epochs_no_improve': epochs_no_improve,
    }, path)

# TRAINING LOOP (with validation, early stopping, checkpointing)
# ══════════════════════════════════════════════════════════════════════════
#check if already trained model exist upto some epochs
if RESUME and os.path.exists(LATEST_MODEL_PATH):
    checkpoint = torch.load(LATEST_MODEL_PATH, weights_only=False)

    model.load_state_dict(checkpoint["model_state_dict"])
    optimizer.load_state_dict(checkpoint["optimizer_state_dict"])
    scheduler.load_state_dict(checkpoint["scheduler_state_dict"])

    start_epoch = checkpoint["epoch"] + 1
    best_val_rate = checkpoint["best_val_rate"]

    best_epoch = checkpoint.get("best_epoch", checkpoint["epoch"])
    epochs_no_improve = checkpoint.get("epochs_no_improve", 0)

    print(f"Resuming training from epoch {start_epoch}")
else : 
    start_epoch= 1   
    best_val_rate = -np.inf
    best_epoch = 0
    epochs_no_improve = 0 #How many consecutive epochs have NOT improved the validation rate?

print(f"\n{'Epoch':>6}  {'Train Loss':>11}  {'Train R':>9}  {'Val R':>9}  "
      f"{'MF R':>9}  {'%MF':>7}  {'LR':>9}  {'ES cnt':>7}  {'Best R':>9}")
print("-" * 95)

for epoch in range(start_epoch, MAX_EPOCHS + 1):
    # ── Train phase ──────────────────────────────────────────────────────
    model.train()
    epoch_losses = [] 
    train_net_rates = [] #They will collect one value per batch

    for H_tensor, H_complex in train_loader: # The loop processes one batch at a time.
        H_tensor = H_tensor.to(device)

        # Forward: predict analog precoder F_RF
        F_RF = model(H_tensor) # (batch,M,K) --> (1024,M,Nrf)

        # Loss (surrogate, differentiable), consuming the exact same H_tensor representation the model just consumed.
        
        loss = concentrated_mse_loss(H_tensor, F_RF, noise_power, P_t) # average concentrated MSE over all 1024 channel realizations in the batch.

        # clear previous gradients
        optimizer.zero_grad()
        #Bckpropogate using the loss
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0) #scales all gradients if the overall their overall norm exceeds 5.
        #update parameters
        optimizer.step()
        # Adam performs W_new= W_old − η⋅Update
        epoch_losses.append(loss.item())

        # Track actual training sum-rate (non-differentiable, for logging
        # only), using the KKT digital precoder -- fed the same H_tensor --
        # plus the numpy-based sum_rate() metric.
        with torch.no_grad():
            F_BB, _, _ = kkt_digital_precoder_torch(H_tensor, F_RF, noise_power, P_t)
            F_RF_dt = F_RF;
            train_net_rates.append(sum_rate_torch( H=H_tensor, F_RF=F_RF, F_BB= F_BB, noise_power= noise_power, P_t=P_t).item())
    avg_train_loss = float(np.mean(epoch_losses))  # Training loss (concentrated mse) per epoch
    avg_train_rate = float(np.mean(train_net_rates)) #avg sum rate per epoch

    # Now The first half of the epoch that is update the network weights is done.

    # ── Validation phase 

    avg_val_rate, avg_mf_rate = evaluate(val_loader, model, val_mf_rates_cached)
    pct_of_mf = 100.0 * avg_val_rate / avg_mf_rate if avg_mf_rate != 0 else float('nan')
    train_loss_history.append(avg_train_loss)
    train_rate_history.append(avg_train_rate)
    val_rate_history.append(avg_val_rate)
    # Step the LR scheduler on validation sum-rate (maximize).
    scheduler.step(avg_val_rate) #This scheduler monitors Validation Sum Rate
    current_lr = optimizer.param_groups[0]['lr']

    # ── Early stopping / checkpointing 
    if avg_val_rate > best_val_rate + ES_MIN_DELTA:
        best_val_rate = avg_val_rate
        best_epoch = epoch
        epochs_no_improve = 0
        save_checkpoint(MODEL_2_PATH, epoch, best_val_rate, best_epoch,epochs_no_improve) # epoch is current and best epoch 
    else:
        epochs_no_improve += 1
    save_checkpoint(
    LATEST_MODEL_PATH,
    epoch,
    best_val_rate,
    best_epoch,
    epochs_no_improve,
    )

    print(f"{epoch:>6}  {avg_train_loss:>11.4f}  {avg_train_rate:>7.3f} b/s  "
          f"{avg_val_rate:>7.3f} b/s  {avg_mf_rate:>7.3f} b/s  {pct_of_mf:>6.1f}%  "
          f"{current_lr:>9.2e}  {epochs_no_improve:>7}  {best_val_rate:>7.3f} b/s")

    if epochs_no_improve >= ES_PATIENCE:
        print(f"\nEarly stopping triggered at epoch {epoch} "
              f"(no improvement for {ES_PATIENCE} epochs). "
              f"Best val sum-rate: {best_val_rate:.3f} b/s at epoch {best_epoch}.")
        break


print(f"\nTraining finished. Best validation sum-rate: {best_val_rate:.3f} b/s "
      f"at epoch {best_epoch}. Checkpoint: {MODEL_2_PATH}")

#PLOTs
#Loss vs Epochs
plt.figure(figsize=(7,5))
plt.plot(train_loss_history)
plt.xlabel("Epoch")
plt.ylabel("Concentrated MSE Loss")
plt.title("Training Loss vs Epoch")
plt.grid(True)
plt.tight_layout()
plt.savefig("loss_vs_epoch.png", dpi=300, bbox_inches="tight")   # Save
plt.show()
#Sum rate vs Epochs
plt.figure(figsize=(7,5))
plt.plot(train_rate_history, label="Training")
plt.plot(val_rate_history, label="Validation")
plt.xlabel("Epoch")
plt.ylabel("Average Sum Rate (bps/Hz)")
plt.title("Sum Rate vs Epoch")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("sum_rate_vs_epoch.png", dpi=300, bbox_inches="tight")   # Save
plt.show()

#TEST SET EVALUATION

print("\nLoading best checkpoint for final test evaluation...")
checkpoint = torch.load(MODEL_2_PATH, map_location=device)
model.load_state_dict(checkpoint['model_state_dict'])

avg_test_rate, avg_test_mf_rate = evaluate(test_loader, model, test_mf_rates_cached)
pct_test_mf = 100.0 * avg_test_rate / avg_test_mf_rate if avg_test_mf_rate != 0 else float('nan')

print(f"\n{'='*55}")
print(f"Final test sum-rate      : {avg_test_rate:.3f} b/s")
print(f"Matched-filter baseline  : {avg_test_mf_rate:.3f} b/s")
print(f"Percentage of MF perf.   : {pct_test_mf:.1f}%")
print(f"Best checkpoint epoch    : {checkpoint['epoch']}")
print(f"{'='*55}")
